export const projects = [
    {
      title: "KiminoApp – Salon Booking App (Ongoing)",
      description: "KiminoApp is a salon booking app designed for customers to explore nearby salons, view services, and book appointments seamlessly. The user app focuses on real-time booking, intuitive UI, and smart time-slot adjustments.",
      features:["Firebase Phone Authentication",
        "Service Browsing with categories and filters",
        "Smart Appointment Booking with auto-adjusted gaps",
        "Real-Time Data Sync using Firestore",
        "Responsive UI built using XML and ConstraintLayout",
        "Push Notifications for appointment reminders"],
      demo:"",//"https://drive.google.com/file/d/1LhfTNepI5PdnjYN5CAk1_hqRkmfjsT3R/preview",
      src1: "../portfolio/assets/images/kiminoimg01.png",
      src2: "../portfolio/assets/images/kiminoimg02.png",
      linkText:"(Private)",
      url: "https://github.com/Pranay-Mondal?tab=repositories",
      color: "#005DFF"
    },
    { 
      title: "Kimino Partner – Salon Owner App (Ongoing)",
      description: "Kimino Partner is the business-side Android application for salon owners, built to manage bookings, services, and employee schedules in real-time. It complements the KiminoApp customer app by providing tools for efficient salon management.",
      features:["Login via Firebase Phone Authentication",
        "Add and Manage Services (with pricing & duration)",
        "View and Manage Appointment Bookings",
        "Employee Listing and Schedule View",
        "Real-Time Data Sync using Firestore",
        "Responsive UI built using XML and ConstraintLayout"],
      demo:"",//"https://drive.google.com/file/d/1LhfTNepI5PdnjYN5CAk1_hqRkmfjsT3R/preview",
      src1: "../portfolio/assets/images/kiminopartner01.png",
      src2: "../portfolio/assets/images/kiminopartner02.png",
      linkText:"(Private)",
      url: "https://github.com/Pranay-Mondal?tab=repositories",
      color: "#0079C5"
    },
    {
      title: "ShyHi – Real-Time Messaging App",
      description: "ShyHi is a real-time messaging app that allows users to create profiles, connect with others, and chat instantly. It focuses on clean UI, fast message delivery, and secure communication using Firebase.",
      features:["Firebase Authentication",
        "Real-Time One-on-One Chat using Firebase Realtime Database",
        "User Profile Creation and Friend Adding",
        "Live Message Sync with Instant Delivery",
        "Responsive UI built using XML and ConstraintLayout"],
      demo:"https://drive.google.com/file/d/1E4jOlG2ZeIbo7YSEFE0vTe_lg8vIG_I9/preview",
      src1: "../portfolio/assets/images/shiportfolio.png",
      src2: "../portfolio/assets/images/shiimg01.png",
      linkText:"GitHub",
      url: "https://github.com/Pranay-Mondal?tab=repositories",
      color: "#005C96"
    },
    {
      title: "Tic Tac Toe – Classic Game with AI",
      description: "This is a mobile Tic Tac Toe game where users can play solo against AI or with a friend. The game includes sound effects, difficulty levels, and a polished UI designed for a smooth user experience.",
      features:["Play with Friend or Against AI (Hard mode)",
        "Minimax Algorithm for Hard Mode AI",
        "Interactive Sound Effects and Turn-Based Animations",
        "Clean UI with Responsive Layout in XML"],
      demo:"https://drive.google.com/file/d/1CDaUmSfb4n4QEzoz8pA6dFlwTLXMw65S/preview",
      src1: "../portfolio/assets/images/tttimg01.png",
      src2: "../portfolio/assets/images/tttimg01.png",
      linkText:"GitHub",
      url: "https://github.com/Pranay-Mondal?tab=repositories",
      color: "#003F67"
    },
    {
      title: "Spotify Clone – Music Streaming Website",
      description: "A full-stack Spotify-inspired web application that allows users to browse albums, play songs, and enjoy seamless audio streaming with a clean, responsive UI. Built to mimic the core functionality of Spotify, this clone provides a real-world music player experience.",
      features:["Responsive Music Player UI with Play/Pause, Seek & Volume Controls",
        "Album & Track Browsing",
        "Clean Modular Codebase"],
      demo: "",//"https://drive.google.com/file/d/1LhfTNepI5PdnjYN5CAk1_hqRkmfjsT3R/preview",
      src1: "../portfolio/assets/images/spotitycloneimg01.png",
      src2: "../portfolio/assets/images/spotifycloneimg01.png",
      linkText:"GitHub",
      url: "https://github.com/Pranay-Mondal/SpotyfiClone",
      color: "#052941"
    }
  ]